---
title: "Replication Crisis Notebook"
output: html_notebook
---

Loading libraries that will be used during this process. 
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(stringr)
library(skimr)
library(splitstackshape)
library(janitor)
```

Loading the csv file

```{r}
#loading the csv files and then joining them in to one data base
  ##converting blanks in to NA

#2010 data bases
data.10.o <- read.csv ("2010_no_articles.csv", na.strings = c("", "NA"))
data.10.a <- read.csv ("2010_yes_articles.csv", na.strings = c("", "NA"))

#2011 data bases
data.11.o <- read.csv ("2011_no_articles.csv", na.strings = c("", "NA"))
data.11.a <- read.csv ("2011_yes_articles.csv", na.strings = c("", "NA"))

#2012 databases
data.12.o <- read.csv ("2012_no_articles.csv", na.strings = c("", "NA"))
data.12.a <- read.csv ("2012_yes_articles.csv", na.strings = c("", "NA"))

#2013 databases
data.13.o <- read.csv ("2013_no_articles.csv", na.strings = c("", "NA"))
data.13.a <- read.csv ("2013_articles.csv", na.strings = c("", "NA"))

#2014 databases
data.14.a <- read.csv ("2014_articles.csv", na.strings = c("", "NA"))
data.14.o <- read.csv ("2014_other.csv", na.strings = c("", "NA"))

#2015 databases
data.15.a <- read.csv ("2015_articles.csv", na.strings = c("", "NA"))
data.15.o <- read.csv ("2015_other.csv", na.strings = c("", "NA"))

#2016 database
  ## everything fit in one for 2016
data.16.all <- read.csv ("2016_all.csv", na.strings = c("", "NA"))

#2017 database
  ## everything fir in one for 2017
data.17.all <- read.csv ("2017_all.csv", na.strings = c("", "NA"))

#2018 database
data.18.a <- read.csv ("2018_articles.csv", na.strings = c("", "NA"))
data.18.o <- read.csv ("2018_other.csv", na.strings = c("", "NA"))

#2019 database
data.19.a <- read.csv ("2019_articles.csv", na.strings = c("", "NA"))
data.19.n <- read.csv ("2019_notes.csv", na.strings = c("", "NA"))
data.19.o <- read.csv ("2019_other.csv", na.strings = c("", "NA"))

#2020 database
data.20.n <- read.csv ("2020_notes.csv", na.strings = c("", "NA"))
data.20.o <- read.csv ("2020_other_articles.csv", na.strings = c("", "NA"))
```

```{r}
#putting the databases together into one
data.original <- rbind(data.10.a, data.10.o,
          data.11.a, data.11.o, 
          data.12.a, data.12.o, 
          data.13.a, data.13.a,
          data.14.a, data.14.o,
          data.15.a, data.15.o,
          data.16.all,
          data.17.all,
          data.18.o, data.18.a,
          data.19.a, data.19.n, data.19.o,
          data.20.n, data.20.o)
```


```{r include=FALSE}
#cleaning the csv file
  ## discarding some of the columns that won't be used
  ## renaming the column titles so they're not capitalized
  ## converting lack of information notes in to NA strings
  ## adding an id to each column

data.original <- data.original %>%
 select(-Art..No., -Molecular.Sequence.Numbers, -Chemicals.CAS,-Tradenames, -Manufacturers, -Funding.Text.1, -Funding.Text.2, -Funding.Text.3, -Funding.Text.4, -Funding.Text.5, -Funding.Text.6, -Funding.Text.7, -Funding.Text.8, -Funding.Text.9, -Funding.Text.10, -Correspondence.Address,  -Abbreviated.Source.Title)
```

```{r}
#renaming the columns for easier handling
names(data.original) <- c("authors", "author.id", "title", "year", "source.title", "volume", "issue", "page.start", "page.end", "page.count", "cited.by", "doi", "link", "affiliations", "author.affiliations", "abstract", "author.keywords", "index.keywords", "funding.details", "references", "editors", "sponsors", "publisher", "conference.name", "conference.date", "conference.location", "conference.code", "issn", "isbn", "coden", "pubmed.id", "original.language", "document.type", "publication.stage", "open.access", "source", "eid")
```

```{r}
#extracting the unique instances
data.original <- unique(data.original)
```

```{r}
#checking how many NAs exist within each column
colSums(is.na(data.original))

##UPDATE HERE WHAT THE NUMBERS ARE BEFORE I RUN THEM
  ##RETRACT COLUMNS THAT ARE TOTALLY EMPTY

#all columns (except isbn) are totally empty columns
  #isbn has one 1 row with data
data.original <- data.original %>%
 select(-editors, -sponsors, -conference.name, -conference.date, -conference.location, -conference.code)
```

```{r}
#adding a unique id code for all of the columns
data <- data.original %>%
  mutate(id = row_number())
```

```{}
#checking which columns use "[No x available]" format
  ##to be able to copy that format and replace with NA instead

data %>% filter(grepl("available]", authors))
#[No author name available]

data %>% filter(grepl("available]", author.id))
#[No author id available]

#none of these have inserted categories
data %>% filter(grepl("available]", title))
data %>% filter(grepl("available]", year))
data %>% filter(grepl("available]", source.title))
data %>% filter(grepl("available]", volume))
data %>% filter(grepl("available]", issue))
data %>% filter(grepl("available]", page.start))
data %>% filter(grepl("available]", page.end))
data %>% filter(grepl("available]", page.count))
data %>% filter(grepl("available]", cited.by))
data %>% filter(grepl("available]", doi))
data %>% filter(grepl("available]", link))
data %>% filter(grepl("available]", affiliations))
data %>% filter(grepl("available]", author.affiliations))
data %>% filter(grepl("available]", abstract))
#[No abstract available]

data %>% filter(grepl("available]", author.keywords))
data %>% filter(grepl("available]", index.keywords))
data %>% filter(grepl("available]", funding.details))
data %>% filter(grepl("available]", references))
data %>% filter(grepl("available]", publisher))
data %>% filter(grepl("available]", issn))
data %>% filter(grepl("available]", isbn))
data %>% filter(grepl("available]", coden))
data %>% filter(grepl("available]", pubmed.id))
data %>% filter(grepl("available]", original.language))
data %>% filter(grepl("available]", document.type))
data %>% filter(grepl("available]", publication.stage))
data %>% filter(grepl("available]", open.access))
data %>% filter(grepl("available]", source))
data %>% filter(grepl("available]", eid))
```


```{r}
#replacing text about missing data for NA instead in the columns that use text to indicate missing information
data.original <- data.original %>%
  mutate(authors = na_if(authors, "[No author name available]")) %>%
  mutate(author.id = na_if(author.id, "[No author id available]")) %>%
  mutate(abstract = na_if(abstract, "[No abstract available]"))
```

```{}
#summarizing the data to observe what is missing
skim(data)
str(data)
```


```{r}
#calculating the number of articles by volume/year
number.volumes <- data %>% count(volume)
#renaming
names(number.volumes) <- c("volume", "n.items.by.year")

#calculating the number of articles by issue
number.issues <- data %>% count(issue)
#renaming
names(number.issues) <- c("volume", "n.items.by.issue")

#calculating the number or issues by year
number.issues.by.year <- data %>%
  group_by(year) %>%
  count(issue) %>%
  select(year, issue) %>%
  count(year)

#renaming the column to be representative of content, number of issues
names(number.issues.by.year) <- c("year", "n.of.issues")
```


```{r}
# identifying tiles, abstracts, author keywords and index keywords with my own keywords
  ## keywords: Replication crisis, replication crisis, Replicability crisis, replicability crisis, Reproducibility crisis, reproducibility crisis

data.title <- data %>%
  filter(grepl("Replication crisis|replication crisis|Replicability crisis|replicability crisis|Reproducibility crisis|reproducibility crisis", title))

data.abstract <- data %>%
  filter(grepl("Replication crisis|replication crisis|Replicability crisis|replicability crisis|Reproducibility crisis|reproducibility crisis", title))

data.author.keywords <- data %>%
  filter(grepl("Replication crisis|replication crisis|Replicability crisis|replicability crisis|Reproducibility crisis|reproducibility crisis", title))

data.index.keywords <- data %>%
  filter(grepl("Replication crisis|replication crisis|Replicability crisis|replicability crisis|Reproducibility crisis|reproducibility crisis", title))

#putting all of the categories back together 
data.replication <- do.call("rbind", list(data.title, data.abstract, data.author.keywords, data.index.keywords))

#deleting any articles that might have replicated
data.replication <- data.replication %>%
  distinct(id, .keep_all = TRUE)
```


```{r}
#splitting author.id, 
  ##in to separate columns using the splitstackshape library, which doesn't require you to know the total a column needs to be split in

data.replication <- cSplit(data.replication, "author.id", sep=";")

data.replication <-  cSplit(data.replication, "authors", sep=",")
  
data.replication <-  cSplit(data.replication, "affiliations", sep=";")

data.replication <- cSplit(data.replication, "index.keywords", sep=";")
  
data.replication <- cSplit(data.replication, "references", sep=";")

data.replication <- cSplit(data.replication, "author.keywords", sep=";")
```


```{r}
# next steps
  ## doing the data visualizations that i'm interested in
  ## pin pointing what visualizations i'm interested in making and why i'm choosing those
  ## randomly selecting 5 different articles to qual-code

```








